### PR TITLE
Use the latest astroquery from pip

### PR DESCRIPTION
**Pull request by bsipocz**
This should fix the caching issue

cc @tomdonaldson @stargaser

### CODE REVIEW

**Review by stargaser — COMMENTED** [review]
I tried out this new environment file by removing and re-installing the navo-env environment. I still got astroquery 0.4.6. Is there something else I need to do?

The installation instructions have been sent to the workshop participants, so we might want to hold off on making this change until after the AAS 242 workshop, once we are satisfied that it works as desired.

**Comment by bsipocz** [comment]
OK, sounds good. Then the instructors need to keep in mind the caching issue from #118 (though as the participants have a new install, I suspect they won't run into it)

**Comment by bsipocz** [comment]
Getting still astroquery 0.4.6 is weird though, I'll have a closer look in a bit.

**Comment by bsipocz** [comment]
@alaity47 - you've tested the environment creation and update, could you check whether this PR works for you to get a newer (dev versioned) astroquery?

**Comment by bsipocz** [comment]
I converted this to a draft as apparently it's not yet working (CI failure looks unrelated though)

**Comment by zoghbi-a** [comment]
> I converted this to a draft as apparently it's not yet working (CI failure looks unrelated though)

The CI failure is related to #128. I fixed it in #129.

**Comment by bsipocz** [comment]
Thanks for the CI fix. I yet to come back to this and dive into the rabbit hole to see why the older release is being picked up.

**Comment by bsipocz** [comment]
OK, so it's after all not a big mystery, just needed a careful look.

1) the jobs that use the `environment.yml` properly pick up the dev version
2) fixed tox and the env check that they don't actually install an older version
3) however, it's not really possible to do the pre-release install with the pip requirements file as `--pre` is a global option, so if we specify it, it will install a pre-release of all the dependencies (given there is an actual pre-release for them).

**Review by stargaser — APPROVED** [review]
I tried making a new environment and I got the development version. Works as expected. I don't understand why it didn't work for me the first time around.

I don't understand the CI failures but I don't think those need to hold up this PR.

**Comment by bsipocz** [comment]
>  I don't understand why it didn't work for me the first time around.

I had a typo there for your first time around.

**Pull request merged**
