### PR TITLE
Adding minimum numpy version

### LINKED ISSUE #87: MAINT: decide minimum numpy dependency
Latest numpy and oldest astropy is not compatible (the reason for #86), but rather than bumping the minimum required astropy version, I would suggest to define a  minimum numpy instead, and it to be 1.18, which is the minimum numpy corresponding to the minimum astropy we have.

We can then always require a newer one if/when we run into compatibility issues.

### PR DESCRIPTION
**Pull request by bsipocz**
This is to fix #87 and hopefully it #86 (and failing CI in the other open PRs, too).

It it comes back with a full green status, I would suggest to get this merged asap.

### CODE REVIEW

**Comment by bsipocz** [comment]
@pllim - I'm sorry for tagging you here, but have you seen similar failures before? I mean I would not expect these compiled API  compatibility issues when all the packages are installed together. (if it doesn't ring a bell, don't need to try to dig into it, I'll cook up a workaround, but first asking maybe you have a ready to go solution already)

**Comment by pllim** [comment]
If you are asking about the oldest version job, it does look weird. It reports `pyvo==1.2` installed but somehow cannot find `vo` when you `import pyvo as vo`. Unfortunately, I am not familiar with the contents nor infrastructure here to know what is going on. What numpy version was the oldest version job using before? Maybe your combo isn't really compatible with the oldest supported numpy here?

The dev job failure looks like something else (`access_url`).

**Comment by bsipocz** [comment]
Oh, my reading is that the real issue is somehow with numpy, at this point I assume the rest are side effects:

https://github.com/NASA-NAVO/navo-workshop/runs/8037595695?check_suite_focus=true#step:5:2019

```
 ---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xd
```

**Comment by bsipocz** [comment]
(the dev job is a real upstream, pyvo issue and totally separate where there is a non backward compatible API change merged, and haven't yet resolved how to go ahead, whether to do proper deprecation or call it a day and break downstream. I'm sorry that I haven't been verbose enough to point out that the only mystical issue here is with the `oldestdeps` job)

**Comment by pllim** [comment]
Maybe double check that all the oldest dep actually don't secretly try to upgrade numpy in their own pins?

**Comment by bsipocz** [comment]
yeah, my guess was that maybe it installs numpy and a bunch of stuff, and then downgrade a few, but not all of them. I'll check on this idea. Thanks for brainstorming on this.

**Review by tomdonaldson — APPROVED** [review]
LGTM.  Thanks for dealing with this @bsipocz !

**Comment by bsipocz** [comment]
No worries. Let's hope that in the future I'll get the notifications from the cron failures, it's still rather a mystery why I get it from some repos but not for the others.

**Pull request merged**
