### PR TITLE
Switch ipynb to myst markdown

### PR DESCRIPTION
**Pull request by zoghbi-a**
This PR addresses issue #69. It switches the notebooks files (.ipynb) to markdown, which can be opened with jupyter notebook (or inside jupyterlab) when `jupytext` is installed.

- The `.ipynb` files were converted to `.md` files
- Added `jupytext` as a dependency (in envionment.yaml and check_env.py)

### CODE REVIEW

**Comment by zoghbi-a** [comment]
Changing from `ipynb` to `md` breaks how the tests are run. Specifically, `pytest --nbval` cannot be run directly as we no longer have notebook files. My quick search/tests suggests that the following is one possible way to do it:
`jupytext --pipe-fmt ipynb --check 'pytest --nbval {}' QuickReference.md`
This however doesn't seem to work with wildcard file selection, so one has to do it for every relevant file.

I will keep digging. Suggestions are welcome, @bsipocz.

**Comment by zoghbi-a** [comment]
@bsipocz suggested the following that is used in numpy notebooks:
`bash -c 'find content -name "*.md" | grep -vf ignore_testing | xargs jupytext --to notebook '`

**Comment by zoghbi-a** [comment]
@bsipocz, @tomdonaldson, @stargaser.
This is ready for review. The changes I made are:
- Add `jupytext` as a dependency
- Use `jupytext` to convert the `ipynb` notebooks to `myst`.
- Fixes to the Ci so `jupytext` is called first to convert the `.md` notebooks to `.ipynb` so the tests with `pytest --nbval` work and the docs are generated from the executed notebooks. The CI seems to works except for `windows-latest` which is giving a permission error when trying to upgrade one library that I couldn't fix (@bsipocz, you help is appreciated).
- The rendered notebooks appear correct.

**Comment by bsipocz** [comment]
New PR for this is #135  as github landed in "Processing diff" for longer than an hour.

**Comment by bsipocz** [comment]
(And now reopen is enabled)

**Pull request closed without merging**
