### PR TITLE
Rename notebooks and move them to 'content' subdirectories

### PR DESCRIPTION
**Pull request by tomdonaldson**
This is our initial attempt at reorganizing the workshop content.  

- Cheat sheet ("CS_") QuickReference notebooks were moved to `content/reference_notebooks`.
- Use case exercise and solutions notebooks were moved to `content/use_case_notebooks` and renamed to indicate the nature of the use case (e.g., `proposal_prep.md` and `proposal_prep_solution.md`).

While trying out some different names, I noticed that for long-ish names the last part of the name can be lost in certain displays like the jupyter lab file explorer and in browser tab titles.  

Another minor observation is that the `<use_case_name>_solution.md` files show up before their corresponding  `<use_case_name>.md` file in the jupyter file explorers.  This seems odd to me (and is different from the order I see with `ls` on my Mac).

### CODE REVIEW

**Comment by stargaser** [comment]
Since we named the subdirectory `use_case_notebooks` and not `exercise_notebooks`, I am in favor of adding `_exercise`, like `candidate_list_exercise.md`. Then I expect Jupyterlab would order the notebooks the way we want.

**Comment by tomdonaldson** [comment]
> Since we named the subdirectory `use_case_notebooks` and not `exercise_notebooks`, I am in favor of adding `_exercise`, like `candidate_list_exercise.md`. Then I expect Jupyterlab would order the notebooks the way we want.

That makes sense to me.  I made that change.

**Comment by stargaser** [comment]
The renaming looks good to me, and no one has raised objections. Does @bsipocz need to change the CI/html-building as part of this PR before it can be merged?

**Review by stargaser — APPROVED** [review]
Looks good to me. The NAVO Python Working Group has had plenty of time to comment on it and no further suggestions or comments have been made.

@bsipocz said she intended to fix the CI in the PR, but that she won't object if we merge it as is, as it will be a little while before she gets to it.

**Pull request merged**
