### PR TITLE
Switch ipynb to myst markdown

### PR DESCRIPTION
**Pull request by zoghbi-a**
[Re-doing]
This PR addresses issue #69. It switches the notebooks files (.ipynb) to markdown, which can be opened with jupyter notebook (or inside jupyterlab) when `jupytext` is installed.

- The `.ipynb` files were converted to `.md` files
- Added `jupytext` as a dependency (in envionment.yaml and check_env.py)

### CODE REVIEW

**Comment by tomdonaldson** [comment]
Re: the temporary fix mast table name (https://github.com/NASA-NAVO/navo-workshop/pull/135/commits/69631cb4de16e6bb150624bcf62a961cbd616446):

The table name has been reverted to its previous capitalization, so is now `dbo.DetailedCatalog` again.

**Comment by bsipocz** [comment]
Thanks @tomdonaldson! I'll remove that temporary commit when I come up with a solution for windows.

**Comment by bsipocz** [comment]
The windows failure was due to a conda vs pip install issue, basically the system didn't let pip reinstall a package executable installed by conda. Workaround was to pip install it in the environment file, too.


However, in the meantime there are new notebook failures which also present on `main`. I don't yet see whether they are transient, and would suggest to wait a day and restart things and report upstream if they will be still present.

**Review by bsipocz — APPROVED** [review]
Everything is passing now, so I'm merging. 

However, some of the test runs need to be restarted multiple times due to various service errors, which shows the notebooks are not exactly robust, and we may need to rethink whether they can be improved (maybe some longer timeouts, or limited return values could do the trick, etc.)

**Comment by bsipocz** [comment]
Thanks @zoghbi-a!

**Pull request merged**
